pipeline {
    agent any
    parameters {
        // choice(name: 'Deploy to', ch)
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                npm run build
            }
        }
        stage('Test') {
            when {
                expression {
                    (BRANCH_NAME == 'd_dev' || BRANCH_NAME == 'main') && CODE_CHANGES == true
                }
            }
            steps {
                echo 'Testing..'
                 npm run test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }

    post {
        always {

        }
        failure {

        }
    }
}