version: '0.2'
name: d_stack
services:
  fullstack:
    build:
      context: js_fullstack
      target: runner
    networks:
      - app_network
    ports:
      - "3000:3000"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - app_network
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1

  py-tasks:
    build:
      context: py-task
      dockerfile: Dockerfile
    depends_on:
      - celery
    ports:
      - 5000:5000
    working_dir: /app    
    command: flask --app main run
  
  celery:
    build:
      context: py-task
      dockerfile: Dockerfile
    depends_on:
      - redis
    working_dir: /app  
    command: celery -A main worker --loglevel INFO

  flower:
    build:
      context: py-task
      dockerfile: Dockerfile
    depends_on:
      - celery
    ports:
      - 5555:5555
    working_dir: /app    
    command: celery -A main flower

  liquibase:
    build:
      context: liquibase
    depends_on:
      - db
    volumes:
      - ./liquibase/conf/changelog/:/liquibase/changelog/
    networks:
      - app_network
    command: --defaults-file=/liquibase/changelog/liquibase.properties update  

networks:
  app_network: {}

volumes:
  db-data: {}
