version: '0.2'
name: d_stack
services:
  fullstack:
    build:
      context: js_fullstack
      target: runner
    networks:
      - app_network
    ports:
      - "3000:3000"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - app_network
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  liquibase:
    build:
      context: liquibase
    depends_on:
      - db
    volumes:
      - ./liquibase/conf/changelog/:/liquibase/changelog/
    networks:
      - app_network
    command: --defaults-file=/liquibase/changelog/liquibase.properties update

networks:
  app_network: {}

volumes:
  db-data: {}
