version: '0.1'
name: py-task-django
services:
  # py-tasks-django:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     depends_on:
  #       - celery
  #     ports:
  #       - 5000:5000
  #     working_dir: /app
  #     command: python main.py

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6380
    command: redis-server --save 20 1 --port 6380

  celery:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      depends_on:
        - redis
      working_dir: /app
      command: celery -A task_app worker -l INFO
  
  beat:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      depends_on:
        - redis
      working_dir: /app
      network_mode: host #only use in Dev env
      command: celery -A task_app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler